version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mentor_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ДОБАВЛЕНО: Докер будет каждые 3 секунды пинговать базу встроенной утилитой pg_isready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mentor_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: mentor_db
    depends_on:
      db:
        # ДОБАВЛЕНО: Ждем не просто старта контейнера, а "здорового" статуса от healthcheck
        condition: service_healthy
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend

volumes:
  pgdata: